
 import javax.swing.JOptionPane;
 import java.sql.Connection;
import java.sql.*;
import javax.swing.*;
   import java.sql.DriverManager;
 import java.sql.ResultSet;
import java.text.SimpleDateFormat;
 import javax.swing.DefaultComboBoxModel;

 
public class tambah_jadwal extends javax.swing.JFrame {

    private ResultSet rs;

    /**
     * Creates new form buat_jadwal
     */
    public tambah_jadwal() {
        initComponents();
        isikelas();
        isiblok();
         isiguru();
          tahun_ajaran();
          isimapel();
         
        
        
    }
    private void kosong(){
      
       
    }
    
    private void tahun_ajaran() {
    try {
        String sql = "SELECT * FROM tahun_ajaran";
        java.sql.Connection conn = (Connection) koneksi.configDB();
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();
        
        // Bersihkan combo box kelas sebelum menambahkan item baru
        tahun_ajaran.removeAllItems();
        
        // Loop melalui hasil query dan tambahkan nama kelas ke combo box
        while(rs.next()) {
            tahun_ajaran.addItem(rs.getString("tahun_ajaran"));
        }
    } catch(Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
}

     private void isikelas() {
    try {
        String sql = "SELECT * FROM kelas";
        java.sql.Connection conn = (Connection) koneksi.configDB();
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();
        
        // Bersihkan combo box kelas sebelum menambahkan item baru
        kelas.removeAllItems();
        
        // Loop melalui hasil query dan tambahkan nama kelas ke combo box
        while(rs.next()) {
            kelas.addItem(rs.getString("nama_kelas"));
        }
    } catch(Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
}

    
    



 private void isiblok(){
      
       try{
        String sql = "SELECT * from blok";
        java.sql.Connection conn=(Connection)koneksi.configDB();
        java.sql.PreparedStatement pst=conn.prepareStatement(sql);
        rs = pst.executeQuery();
        
        while(rs.next()){
            blok.addItem(rs.getString("id_blok"));
        }
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }
   }
private void isiguru() {
    try {
        String sql = "SELECT * FROM guru";
        java.sql.Connection conn = (Connection) koneksi.configDB();
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();
        
       while(rs.next()){
            guru.addItem(rs.getString("nama_guru"));
        }
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }
}

private void isimapel() {
    try {
        String sql = "SELECT * FROM mapel";
        java.sql.Connection conn = (Connection) koneksi.configDB();
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();
        
       while(rs.next()){
            mapel.addItem(rs.getString("nama_mapel"));
        }
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }
}


  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jammulai = new com.raven.swing.TimePicker();
        jamselesai = new com.raven.swing.TimePicker();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        kelas = new javax.swing.JComboBox<>();
        blok = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        sesi = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        tampilanjamselesai = new javax.swing.JTextField();
        tampilanjammulai = new javax.swing.JTextField();
        guru = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        tahun_ajaran = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        mapel = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        jammulai.setDisplayText(tampilanjammulai);

        jamselesai.setDisplayText(tampilanjamselesai);

        jMenu2.setText("Menu");
        jMenu2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jMenuItem1.setText("Dashboard");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Kelas            :");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("Sesi               : ");

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setText("Simpan");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        kelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelasActionPerformed(evt);
            }
        });

        blok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blokActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("Blok              : ");

        sesi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "ISTIRAHAT" }));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("Nama Guru :");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setText("Jam Selesai  :");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setText("Jam Mulai   :");

        jButton3.setText("Show Time");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Show Time");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        tampilanjammulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilanjammulaiActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Tahun ajaran:");

        tahun_ajaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tahun_ajaranActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setText("Nama Mapel:");

        mapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mapelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mapel, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tampilanjamselesai)
                            .addGap(18, 18, 18)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tampilanjammulai, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tahun_ajaran, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(sesi, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(blok, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(kelas, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(guru, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(98, 98, 98)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tahun_ajaran, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(kelas, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(blok, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(sesi, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(guru, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(mapel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jButton3)
                    .addComponent(tampilanjammulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jButton4)
                    .addComponent(tampilanjamselesai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        jMenu3.setText("Menu");
        jMenu3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jMenuItem2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jMenuItem2.setText("Dashboard");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("rewdf");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try {
    // Ambil nama guru dari combo box
    String namaGuru = (String) guru.getSelectedItem(); // Ambil nama guru dari combo box
    String namaMapel = (String) mapel.getSelectedItem(); // Ambil nama mapel dari combo box
    String namaKelas = (String) kelas.getSelectedItem(); // Ambil nama kelas
    String sesiPilihan = (String) sesi.getSelectedItem(); // Ambil sesi yang dipilih

    // Ambil id_tahun_ajaran dari combo box
    String tahunAjaranStr = (String) tahun_ajaran.getSelectedItem(); // Ambil sebagai String

    // Cek apakah tahunAjaranStr valid
    if (tahunAjaranStr == null || tahunAjaranStr.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Tahun ajaran tidak boleh kosong.");
        return; // Kembalikan agar tidak melanjutkan eksekusi
    }

    // Buat koneksi ke database
    java.sql.Connection conn = (Connection) koneksi.configDB();

    // Ambil id_tahun_ajaran dari tabel berdasarkan tahun ajaran yang dipilih
    String sqlIdTahunAjaran = "SELECT id_tahun_ajaran FROM tahun_ajaran WHERE tahun_ajaran = ?";
    java.sql.PreparedStatement pstIdTahunAjaran = conn.prepareStatement(sqlIdTahunAjaran);
    pstIdTahunAjaran.setString(1, tahunAjaranStr);
    java.sql.ResultSet rsIdTahunAjaran = pstIdTahunAjaran.executeQuery();

    int idTahunAjaran = 0; // Default jika tidak ada tahun ajaran ditemukan
    if (rsIdTahunAjaran.next()) {
        idTahunAjaran = rsIdTahunAjaran.getInt("id_tahun_ajaran");
    } else {
        JOptionPane.showMessageDialog(this, "Tahun ajaran tidak ditemukan: " + tahunAjaranStr);
        return; // Kembalikan jika tahun ajaran tidak ditemukan
    }

    // Query untuk mencari id guru berdasarkan nama guru
    String sqlIdGuru = "SELECT id_guru FROM guru WHERE nama_guru = ? AND nama_mapel = ?";
    java.sql.PreparedStatement pstIdGuru = conn.prepareStatement(sqlIdGuru);
    pstIdGuru.setString(1, namaGuru);
    pstIdGuru.setString(2, namaMapel);
    java.sql.ResultSet rsIdGuru = pstIdGuru.executeQuery();

    int idGuru = 0; // Default 0 jika tidak ada id guru yang ditemukan
    if (rsIdGuru.next()) {
        idGuru = rsIdGuru.getInt("id_guru");
    } else {
        JOptionPane.showMessageDialog(this, "Guru tidak ditemukan: " + namaGuru);
        return; // Kembalikan jika guru tidak ditemukan
    }

    // Query untuk mencari id kelas berdasarkan nama kelas
    String sqlIdKelas = "SELECT id_kelas FROM kelas WHERE nama_kelas = ?";
    java.sql.PreparedStatement pstIdKelas = conn.prepareStatement(sqlIdKelas);
    pstIdKelas.setString(1, namaKelas);
    java.sql.ResultSet rsIdKelas = pstIdKelas.executeQuery();

    int idKelas = 0; // Default 0 jika tidak ada id kelas yang ditemukan
    if (rsIdKelas.next()) {
        idKelas = rsIdKelas.getInt("id_kelas");
    } else {
        JOptionPane.showMessageDialog(this, "Kelas tidak ditemukan: " + namaKelas);
        return; // Kembalikan jika kelas tidak ditemukan
    }

    // Jika tidak ada bentrok jadwal, lanjutkan dengan penyimpanan data
    String sqlInsert = "INSERT INTO jadwal (id_kelas, id_blok, sesi, id_guru, jam_mulai, jam_selesai, id_tahun_ajaran, id_mapel) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
    java.sql.PreparedStatement pstInsert = conn.prepareStatement(sqlInsert);
    
    pstInsert.setInt(1, idKelas);
    pstInsert.setString(2, (String) blok.getSelectedItem());
    pstInsert.setString(3, sesiPilihan);
    pstInsert.setInt(4, idGuru); // Set id guru yang ditemukan

    // Konversi string waktu ke format yang diharapkan oleh MySQL
    SimpleDateFormat sdf = new SimpleDateFormat("hh:mm a");
    java.util.Date waktuMulai = sdf.parse(tampilanjammulai.getText());
    java.util.Date waktuSelesai = sdf.parse(tampilanjamselesai.getText());

    // Set waktu mulai dan selesai dalam format yang sesuai
    pstInsert.setTime(5, new java.sql.Time(waktuMulai.getTime()));
    pstInsert.setTime(6, new java.sql.Time(waktuSelesai.getTime()));

    // Set id_tahun_ajaran
    pstInsert.setInt(7, idTahunAjaran);

    // Set id_mapel (pastikan Anda sudah mendapatkan id_mapel dari tabel mapel)
    String sqlIdMapel = "SELECT id_mapel FROM mapel WHERE nama_mapel = ?";
    java.sql.PreparedStatement pstIdMapel = conn.prepareStatement(sqlIdMapel);
    pstIdMapel.setString(1, namaMapel);
    java.sql.ResultSet rsIdMapel = pstIdMapel.executeQuery();

    int idMapel = 0; // Default 0 jika tidak ada id mapel yang ditemukan
    if (rsIdMapel.next()) {
        idMapel = rsIdMapel.getInt("id_mapel");
    } else {
        JOptionPane.showMessageDialog(this, "Mapel tidak ditemukan: " + namaMapel);
        return; // Kembalikan jika mapel tidak ditemukan
    }
    pstInsert.setInt(8, idMapel); // Set id mapel yang ditemukan

    pstInsert.executeUpdate();

    JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
    kosong();
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
}

// Setelah penyimpanan berhasil, kosongkan form
kosong();






    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
jammulai.showPopup(this, 400, 200);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    jamselesai.showPopup(this, 400, 100);    // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void kelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kelasActionPerformed

    private void blokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blokActionPerformed

    private void tampilanjammulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampilanjammulaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tampilanjammulaiActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new dashboard().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new dashboard().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void tahun_ajaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tahun_ajaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tahun_ajaranActionPerformed

    private void mapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mapelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mapelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tambah_guru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tambah_guru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tambah_guru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tambah_guru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tambah_jadwal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> blok;
    private javax.swing.JComboBox<String> guru;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private com.raven.swing.TimePicker jammulai;
    private com.raven.swing.TimePicker jamselesai;
    private javax.swing.JComboBox<String> kelas;
    private javax.swing.JComboBox<String> mapel;
    private javax.swing.JComboBox<String> sesi;
    private javax.swing.JComboBox<String> tahun_ajaran;
    private javax.swing.JTextField tampilanjammulai;
    private javax.swing.JTextField tampilanjamselesai;
    // End of variables declaration//GEN-END:variables
}
